// CLIA v2 LG.com extractor — inject into page, then call __cliaRun(id, catFilter)
window.__cliaRun=async(id,catFilter)=>{
  const cleanSrc=s=>(s||'').split('?')[0];
  const relPath=s=>{const c=cleanSrc(s);const m=c.match(/\/sa_en(\/.*?)(\/jcr:content.*)?$/);return m?m[1]:c;};
  const isProd=s=>s&&s.includes(catFilter);
  const pickDesk=(imgEl)=>{const pic=imgEl.closest('picture');if(pic){const ds=[...pic.querySelectorAll('source')].find(s=>/min-width/.test(s.media||''));if(ds&&ds.srcset)return ds.srcset.split(',')[0].trim().split(/\s+/)[0];}return imgEl.currentSrc||imgEl.src;};
  const measure=(urls)=>Promise.all(urls.map(u=>new Promise(res=>{const im=new Image();im.onload=()=>res({u,w:im.naturalWidth,h:im.naturalHeight});im.onerror=()=>res({u,w:0,h:0});im.src=u.startsWith('http')?u:'https://www.lg.com'+u;})));
  const btn=[...document.querySelectorAll('button')].find(b=>(b.innerText||'').includes('See All Specs'));
  if(btn)btn.click();
  await new Promise(r=>setTimeout(r,400));
  const h1=document.querySelector('h1')?.innerText?.trim()||'';
  const pBox=document.querySelector('.price-box--price,.neo-price--price');
  const curPrice=pBox?.querySelector('.cell-price')?.innerText?.trim().replace(/\s+/g,' ')||'';
  const origPrice=pBox?.querySelector('del')?.innerText?.trim().replace(/\s+/g,' ')||'';
  const memberPrice=(document.querySelector('.price-bottom,.neo-price--bottom')?.innerText||'').replace(/Member Only/i,'').trim();
  const galImgs=[...document.querySelectorAll('.c-gallery__item--display-image img')];
  const seenGal=new Set();const galRaw=[];
  galImgs.forEach(i=>{const d=pickDesk(i);const src=cleanSrc(d);if(!src||seenGal.has(src)||!isProd(src))return;seenGal.add(src);galRaw.push({p:relPath(src),u:src,a:i.alt||''});});
  const modulesRaw=[];
  const blocks=[...document.querySelectorAll('.c-hero-banner, .c-floating-contents, .c-summary-picture, .c-media-contents, .c-text-contents')];
  const seen=new Set();
  blocks.forEach(b=>{let blk=b.closest('.c-wrapper,.cmp-container,.component')||b;if(seen.has(blk))return;
    const imgs=[...blk.querySelectorAll('img')].filter(i=>{const u=pickDesk(i);return isProd(u);}).filter(i=>!i.closest('.c-gallery'));
    if(!imgs.length)return;seen.add(blk);
    const eye=blk.querySelector('.c-text-contents__eyebrow')?.innerText?.trim()||'';
    const head=blk.querySelector('.c-text-contents__headline,.cmp-title__text')?.innerText?.trim()||'';
    const body=blk.querySelector('.c-text-contents__bodycopy')?.innerText?.trim()||'';
    const disc=blk.querySelector('.c-text-contents__disclaimer')?.innerText?.trim()||'';
    const seenImg=new Set();const mi=[];
    imgs.forEach(i=>{const d=pickDesk(i);const src=cleanSrc(d);if(seenImg.has(src))return;seenImg.add(src);mi.push({p:relPath(src),u:src,a:i.alt||''});});
    modulesRaw.push({eye,head,body,disc,imgs:mi});
  });
  const urls=[...new Set([...galRaw.map(g=>g.u),...modulesRaw.flatMap(m=>m.imgs.map(i=>i.u))])];
  const dims=await measure(urls);const dm={};dims.forEach(d=>{dm[d.u]={w:d.w,h:d.h};});
  const gallery=galRaw.map(g=>({p:g.p,a:g.a,w:dm[g.u]?.w||0,h:dm[g.u]?.h||0}));
  modulesRaw.forEach(m=>{m.imgs=m.imgs.map(i=>({p:i.p,a:i.a,w:dm[i.u]?.w||0,h:dm[i.u]?.h||0}));});
  const specArea=document.querySelector('.c-all-specs-area');
  const specs=specArea?[...specArea.querySelectorAll('.c-compare-selling__item')].map(r=>({k:r.querySelector('.c-compare-selling__spec-name')?.innerText?.trim()||'',v:r.querySelector('.c-compare-selling__spec-desc')?.innerText?.trim()||''})).filter(s=>s.k&&s.v):[];
  const result={id,url:location.href,h1,curPrice,origPrice,memberPrice,gallery,modules:modulesRaw,specs};
  const asciiJSON=JSON.stringify(result).replace(/[\u0080-\uffff]/g,c=>'\\u'+('0000'+c.charCodeAt(0).toString(16)).slice(-4));
  localStorage.setItem('CLIA_'+id,asciiJSON);
  const blob=new Blob([asciiJSON],{type:'text/plain;charset=utf-8'});
  window.__CLIA_BLOB__=URL.createObjectURL(blob);
  return {id,size:asciiJSON.length,gal:gallery.length,mods:modulesRaw.length,specs:specs.length,blobUrl:window.__CLIA_BLOB__};
};
'runner ready';
